#!/bin/sh -e

# This allows the kernel module to be loaded.
# Otherwise license incompatibility would prevent
# this from working. This is totally unsupported!
sed -i 's/CDDL/GPL/g' META

./configure \
    --build=$(cc -dumpmachine) \
    --disable-systemd \
    --disable-sysvinit \
    --disable-nls \
    --enable-linux-builtin \
    --prefix=/usr \
    --sysconfdir=/etc

make
make DESTDIR="$1" install

cd module
make
make DESTDIR="$1" install

# Clean up some things we don't need
rm -Rf "$1/usr/share/zfs/zfs-tests"
rm -Rf "$1/usr/lib/dracut/"
rm -Rf "$1/usr/share/initramfs-tools/"
